-- AlterTable
ALTER TABLE `Banner` MODIFY `ma_banner` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `CumRap` MODIFY `ma_cum_rap` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `Ghe` MODIFY `ma_ghe` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `HeThongRap` MODIFY `ma_he_thong_rap` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `LichChieu` MODIFY `ma_lich_chieu` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `Phim` MODIFY `ma_phim` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `RapPhim` MODIFY `ma_rap` INTEGER NOT NULL AUTO_INCREMENT;
